### PR TITLE
Acl2 problems

### PR DESCRIPTION
**Pull request by mezpusz**

### CODE REVIEW

**Comment by mezpusz** [comment]
I created a new PR because the previous was somehow not able to recognize the removed file changes. In theory all files should be there, but whether they don't contain any ACL2 errors is not 100%. I added the list/crafted_assorted problems manually and these surely result in some errors since the outOfBounds function is uninterpreted.

**Review by joe-hauns — APPROVED** [review]

**Comment by hzzv** [comment]
> I added the list/crafted_assorted problems manually and these surely result in some errors since the outOfBounds function is uninterpreted.

Wouldn't it be better then to remove the files which result in errors? In the paper we say that we only provide the translations when possible (and explicitly name the uninterpreted outOfBounds function as one of the constructs which cannot be straightforwardly translated).

**Comment by mezpusz** [comment]
> > I added the list/crafted_assorted problems manually and these surely result in some errors since the outOfBounds function is uninterpreted.
> 
> Wouldn't it be better then to remove the files which result in errors? In the paper we say that we only provide the translations when possible (and explicitly name the uninterpreted outOfBounds function as one of the constructs which cannot be straightforwardly translated).

**Comment by mezpusz** [comment]
> Wouldn't it be better then to remove the files which result in errors?
Yes, we can e.g. only add a function if it doesn't result in parsing errors. If it is not admitted because of non-well-foundedness, it's OK.

**Comment by mezpusz** [comment]
I updated the files:
- The branch in `get` containing the uninterpreted function could be simply removed, it seems ACL2 treats the missing branch as NIL.
- I forgot that ACL2 has no quantifiers and that in most cases, universal quantification of the whole formula gives a different formula, so I removed every formula that had universal quantification inside the formula or existential anywhere. I only found this to be still true after removing the forall:
```(=> (PREF L1 L2)
              (FORALL ((X NAT))
                     (LEQ (CNT L1 X) (CNT L2 X)))))``` Although due to the different quantification it is somewhat different from the problem in smt2 format. What do you think?
- Now all functions are admitted by ACL2 except ROTATELEFT and ROTATERIGHT, since these don't admit a lexicographic ordering.

**Comment by hzzv** [comment]
Thanks for the changes!

>   Although due to the different quantification it is somewhat different from the problem in smt2 format. What do you think? Should we remove this as well?
Let's keep this - the problems are different but (as far as I understand) equivalent.

**Pull request merged**
